version: '4.14'

services: 
    mysqldb:
        image: mysql:latest
        ports:
        - 3306:3306
        environment: 
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=bet_flask
        volumes: 
        - mysqlVolume:/var/lib/mysql
        - mysqlConfig:/etc/mysql
    
    

volumes: 
    mysqlVolume:
    mysqlConfig:
